### ISSUE TITLE
Cannot install plugin

### ISSUE THREAD

**Issue by EnkhAmgalanGanbaatar** [vetyy/helm-ecr#1]
Hi, 

i cannot install the plugin because it promts github credentials. Is it intended so?

Cheers

**Comment by vetyy** [comment]
Hi,

I am not sure, but I think that's standard from Github to ask for credentials when effectively cloning any repository using HTTPS clone URL (https://github.com/vetyy/helm-ecr.git) or you could also install using SSH (git@github.com:vetyy/helm-ecr.git).

But, if that doesn't work for you, you can simple download compiled binary from here: https://github.com/vetyy/helm-ecr/releases

**Comment by EnkhAmgalanGanbaatar** [comment]
Hi sorry for the late response. 
its strange because when i install e.g. the `helm-s3` plugin there is no problem. I have ended up fork this repo which has worked as well. Therefore i think this shoud be something regarding repo setting may be?
