### ISSUE TITLE
Release windows amd64 binary

### ISSUE THREAD

**Issue by gitfool** [vetyy/helm-ecr#4]
Would you please release a windows amd64 binary too?

**Comment by vetyy** [comment]
Hey @gitfool , I released a new version (v0.1.4) with windows binary, please test it and let me know if everything is okay. I don't really have a windows machine available right now.

**Comment by gitfool** [comment]
@vetyy thanks a lot, it worked!

Notes:
* I had to manually drop in the tarball since plugin install is [broken on windows](https://github.com/helm/helm/issues/7117)
* tarball is not structured correctly; I had to move `helmecr.exe` to `bin/helmecr.exe`
* ... it looks like all `0.1.4` tarballs are not structured correctly (whereas all `0.1.3` tarballs are)
* version was not bumped to `0.1.4` in the [plugin.yaml](https://github.com/vetyy/helm-ecr/blob/6020054000094719cba37aaabb8284559803093c/plugin.yaml#L2) (to match release)

**Comment by gitfool** [comment]
@vetyy sorry to bother you but would you be able to fix the above issues and make another release? 🙏

**Comment by vetyy** [comment]
sorry @gitfool I was really busy this week, I fixed existing release of `0.1.4` can you test it now please?

**Comment by gitfool** [comment]
@vetyy LGTM; thanks!
