### ISSUE TITLE
Issue with ECR Credentials

### ISSUE THREAD

**Issue by karthikrengarajan** [vetyy/helm-ecr#5]
Hi, 

I have published helm charts to ECR registry and would like to use fluxcd to deploy the changes. I have installed the plugin to the helm-operator and below are the logs from the helm operator. Please advise if I am missing something.

```
failed to populate Helm index: failed to describe images: NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
ts=2021-06-24T16:35:02.89190834Z caller=release.go:85 component=release release=default-xxxxxxxxx targetNamespace=default resource=default:helmrelease/xxxxxxxxxxxxx helmVersion=v3 error="failed to prepare chart for release: chart unavailable: looks like \"ecr://xxxxxxxxxxxxx.dkr.ecr.eu-west-1.amazonaws.com/xxxxxxxxxxxxx\" is not a valid chart repository or cannot be reached: plugin \"bin/helmecr\" exited with error"
```

**Comment by vetyy** [comment]
Hey @karthikrengarajan,

I am not 100% sure from the error message, but if the ECR URL is correct as mentioned here: https://github.com/vetyy/helm-ecr#helm-operator
I would maybe try to check if the `helm-operator` pod have correct credentials.

The way I do it is using `eks.amazonaws.com/role-arn: arn:aws:iam::<PROJECT_ID>:role/<ROLE_NAME>` annotation that I patch on service account that helm-operator is using.

Not sure how you provide the credentials to your pods.

You could try to use `helm-ecr` locally and verify it works with your ECR repository and its not problem there and its just credentials issue.

Let me know if I can help you debug further.

**Comment by amitkatyal** [comment]
@vetyy, I was trying to pull the chart from the ecr public repo but was getting an error.
Does this plugin work with the public ECR repo as well?

**Comment by vetyy** [comment]
Hey @amitkatyal, unfortunately it doesn't, using public repository requires using different SDK (https://docs.aws.amazon.com/sdk-for-go/api/service/ecrpublic/) and that unfortunately doesn't support methods like `BatchGetImage` `GetDownloadUrlForLayer` which I rely on here, so its so simple to add support for it. I don't think using https://docs.aws.amazon.com/sdk-for-go/api/service/ecr/ for public repositories is possible.

**Comment by amitkatyal** [comment]
@vetyy, Thanks for your quick reply!

**Comment by vetyy** [comment]
Feel free to open again, if you need help
