### ISSUE TITLE
Issues during chart push

### ISSUE THREAD

**Issue by VladVolchkov** [vetyy/helm-ecr#7]
Is it possible to push helm charts into AWS ECR repository using this plugin? I'm facing following error when try to push chart:

```
helm push helm-statsd-exporter-1.0.0.tgz ecr
Error: scheme prefix missing from remote (e.g. "oci://")
```
Chart pull or installation from ECR repository works fine.

**Helm version: v3.8.1
Plugin version: v0.1.4**

**Comment by vetyy** [comment]
Hey, you should be able to push chart using native command like this:
```
helm push helm-test-chart-0.1.0.tgz oci://aws_account_id.dkr.ecr.region.amazonaws.com/
```

**Comment by VladVolchkov** [comment]
Yes, I'm able to push chart using native command, just wanted to clarify is it possible to push chart using plugin, issue can be closed, thank you for fast reply.
